//app file
import '../config.dart';

class AppRoute {
  Map<String, Widget Function(BuildContext)> route = {
    routeName.splash: (p0) => const SplashScreen(),
    routeName.onBoarding: (p0) => const OnBoardingScreen(),
    routeName.login: (p0) => const LoginScreen(),
    routeName.registration: (p0) => const RegistrationPage(),
    routeName.forgot: (p0) => const ForgotScreen(),
    routeName.changePassword: (p0) => const CreatePassword(),
    routeName.otpVerify: (p0) => const OTPScreen(),
    routeName.cartView: (p0) => const CartScreen(),
    routeName.categoryView: (p0) => const CategoryScreen(),
    routeName.homePage: (p0) => const HomeScreen(),
    routeName.profile: (p0) => const ProfileScreen(),
    routeName.wishlist: (p0) => const WishListScreen(),
    routeName.dashboard: (p0) => const Dashboard(),
    routeName.chairData: (p0) => const ChairScreen(),
    routeName.filterData: (p0) => const FurnitureFilterLayout(),
    routeName.checkOut: (p0) => const CheckOutScreen(),
    routeName.shippingDetails: (p0) => const ShippingDetailsLayout(),
    routeName.couponCode: (p0) => const CouponCodeLayout(),
    routeName.trackingOrder: (p0) => const TrackingOrderScreen(),
    routeName.notification: (p0) => const NotificationScreen(),
    routeName.emptyWishList: (p0) => const EmptyWishListLayout(),
    routeName.navigationDrawer: (p0) => const CommonNavigationDrawer(),
    routeName.pageList: (p0) => const PageList(),
    routeName.emptyNotification: (p0) => const EmptyNotification(),
    routeName.emptySearch: (p0) => const EmptySearchLayout(),
    routeName.emptyCart: (p0) => const EmptyCartLayout(),
    routeName.emptyOrderHistory: (p0) => const EmptyOrderLayout(),
    routeName.addNewAddress: (p0) => const AddNewAddress(),
    routeName.addCard: (p0) => const AddCardLayout(),
    routeName.oderTracking: (p0) => const TrackingOrderScreen(),
    routeName.payment: (p0) => const PaymentLayout(),
    routeName.shippingScreen: (p0) => const ShippingOptionScreen(),
    routeName.termsCondition: (p0) => const TermsConditionLayout(),
    routeName.profileSetting: (p0) => const ProfileSettingLayout(),
    routeName.orderHistory: (p0) => const OrderHistoryLayout(),
    routeName.orderDetails: (p0) => const OrderDetailsScreen(),
    routeName.detailsScreen: (p0) => const DetailsScreen(),
    routeName.detailsScreenSecond: (p0) => const SecondDetailsScreen(),
    routeName.currencyScreen: (p0) => const CurrencyScreen(),
    routeName.language: (p0) => const LanguageLayout(),
    routeName.setting: (p0) => const SettingLayout(),
    routeName.help: (p0) => const HelpLayout(),
    routeName.reviews:(p0)=> const ReviewScreen()
  };
}
